### ISSUE TITLE
a list that does not have the same abstract number id as the previous one is stripped on output

### ISSUE THREAD

**Issue by hugo-inacio** [pageseeder/docx#1]
When there is a list that does not have the same abstract number id as the previous one, then it gets ignored on output. Have a look at the input docx [list-error.docx](https://github.com/pageseeder/docx/files/3920043/list-error.docx), and the output psml [output.txt](https://github.com/pageseeder/docx/files/3920042/output.txt).

**Comment by philipru** [comment]
Thanks Hugo, this has been fixed in v0.8.11.
