### ISSUE TITLE
Lists with only w:hyperlink content cause PSML to crash

### ISSUE THREAD

**Issue by hugo-inacio** [pageseeder/docx#2]
The following file:
[List Example.docx](https://github.com/pageseeder/docx/files/5060831/List.Example.docx)
Causes the PSML import to fail. The issue is ( from what I can see) that a list item has only w:hyperlink content. Because of that it does not get added to the global variable $list-paragraphs that includes all list items 

Error message:
```

Type error evaluating ($list-paragraphs/descendant::element()[$vv:v4 = @id]) in xsl:with-param/@select on line 237 column 94 of psml-lists.xsl:
  XTTE0590: An empty sequence is not allowed as the value of parameter $current-node
```

**Comment by philipru** [comment]
This has now been fixed in the v0.8.14 release.

Thanks
